profile = "gpt5"

# Default (can be overridden by profile or CLI)
model = "gpt-5"
approval_policy = "untrusted" # always ask for approval
disable_response_storage = false

[model_providers.openai]
name = "OpenAI using Responses API"
base_url = "https://api.openai.com/v1"
env_key = "OPENAI_API_KEY"
wire_api = "responses"

[model_providers.openai-chat-completions]
name = "OpenAI using Chat Completions"
base_url = "https://api.openai.com/v1"
env_key = "OPENAI_API_KEY"
wire_api = "chat"

[profiles.gpt5]
model = "gpt-5"
model_provider = "openai"
approval_policy = "untrusted"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"

